"""users add column password phone is_active created_at updated_at

Revision ID: 8d70890759f8
Revises: edb89f1e05c3
Create Date: 2025-11-27 19:39:58.649898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d70890759f8'
down_revision = 'edb89f1e05c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_index(batch_op.f('google_id'))
        batch_op.drop_column('google_id')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('google_id'), ['google_id'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
